### ISSUE TITLE
HMD vertically flipped in X-Plane (11 & 12)

### ISSUE THREAD

**Issue by msmarino** [mbucchia/OpenXR-Vk-D3D12#2]
_Applications using OpenGL with an OpenXR runtimes without support for mutable FOV (as reported in XrViewConfigurationProperties) will have rendering upside-down. The necessary code to Y-flip the image is not implemented._

I am supposedly running the latest version of OpenXR and Windows 10 with my G2:
OpenXR: Runtime 110.2204.7007
Windows: 19045.2130 22H2
GPU: RTX3080 10GB + drivers 522.25

WMR Runtime reports
XR_VIEW_CONFIGURATION_TIME_PRIMARY_STEREO
fovMutable: True

I can find no other similar complaints on Google and I am at a loss as to why I am having this problem.

Given that DCS runs PERFECT, I can only assume the problem lies within the X-Plane/D3D12 layers.

Any assistance would be greatly appreciated.

**Comment by mbucchia** [comment]
WMR runtime 110 is largely outdated, please update OpenXR for Windows Mixed Reality from the MS store.

**Comment by mbucchia** [comment]
Not really as you said, nobody else is experiencing this. Must be a setting or some other uncommon incompatibility. 

Are you using OpenXR Toolkit too? If so, can you try without it?

Can you attach the log file? (`%LocalAppData%\XR_APILAYER_NOVENDOR_vulkan_d3d12_interop.log`).

Must upload from the website, not by email.

**Comment by mbucchia** [comment]
My current suspicion is that you have an old version of OpenXR Toolkit which is causing the problem. Version 1.2.0 should work.

**Comment by msmarino** [comment]
2 out of 2

I've gotten lazy with all the automatic updates...  Now I'm the right way
up, back to Laminar to see why my G2 controllers are detected as Oculus and
no buttons work.

Thank you soooo much for the assistance !

**Comment by mbucchia** [comment]
Don't understand what that means. Was the issue resolved?

**Comment by mbucchia** [comment]
The controllers issue is OpenComposite bug. You'll have to take it to OpenComposite not Laminar.
