### ISSUE TITLE
Verify Vulkan 1.1 presence

### ISSUE THREAD

**Issue by bethau** [mbucchia/OpenXR-Vk-D3D12#3]
When validating the adapterLuid in layer.cpp `vkGetPhysicalDeviceProperties2` is used. This is a Vulkan 1.1 feature. The interop layer however does not verify that the user actually created a Vulkan 1.1 instance. When creating a Vulkan 1.0 instance with the interop layer, the error message given is very confusing. It tells the user that the incorrect graphics adapter is used, which is not the case. The correct graphics adapter is used, the user is just not creating a Vulkan 1.1 instance. The interop layer should check for Vulkan 1.1 presence and give a good error message in case it is not present.

Is seems that very recent nvidia drivers have become more strict. Previously they would allow a call to `vkGetPhysicalDeviceProperties2` on a Vulkan 1.0 instance, now the function doesn't return any valid data. Repoing this issue is simple: On latest nvidia drivers, try to use the interop layer with vulkan 1.0.

**Comment by mbucchia** [comment]
Thanks, you are correct, I encountered and fixed this issue in another project that includes this code, but did not backport here!

**Comment by mbucchia** [comment]
Fixed by 0bf812c05c21fc5492709c5abf709295e72ec6ba.
