### ISSUE TITLE
Issues with installer

### ISSUE THREAD

**Issue by neckandthroat** [mbucchia/OpenXR-Vk-D3D12#5]
I almost always get an error saying the install server isn't responding when I open the installer.
After retrying a few times I can get past that and to the actual installer, but I get an error message saying it's not responding.
![image](https://github.com/mbucchia/OpenXR-Vk-D3D12/assets/30828928/6004582e-081a-422c-b2b0-10c92ab3002e)

**Comment by mbucchia** [comment]
This indicates an issue with your windows. There's not much I can do here :(
