### ISSUE TITLE
Beamng enters VR but headset shows black screen

### ISSUE THREAD

**Issue by LexFernetti** [mbucchia/OpenXR-Vk-D3D12#6]
Using a Samsung Odyssey plus on win11 with a gtx1070 and 32gb ram.

Here's the log for troubleshooting.

[XR_APILAYER_MBUCCHIA_vulkan_d3d12_interop.log](https://github.com/mbucchia/OpenXR-Vk-D3D12/files/13433503/XR_APILAYER_MBUCCHIA_vulkan_d3d12_interop.log)

Thank you for your awesome support to VR.

**Comment by mbucchia** [comment]
It's working fine here. Try disabling OpenXR Toolkit and XRNeckSafer.

**Comment by mbucchia** [comment]
Can you also check you're running the latest Nvidia driver? I hope your driver isn't as old as your GPU ^^ :)

**Comment by LexFernetti** [comment]
it was xr neck safer, I disabled it and it worked. Thank you!

**Comment by mbucchia** [comment]
Thanks for letting me know. This is super strange... I'm not even sure how that one could interfere!
